### ISSUE TITLE
Feature request: support for systemd-timesyncd

### ISSUE THREAD

**Issue by rmbleeker** [linux-system-roles/timesync#116]
systemd-timesyncd offers very basic NTP time synchronization support, but is often times sufficient. Is there a reason why this Ansible system role does not support it? If not, is there an interest to receive a pull request for this? Has it maybe been tried before and should I be aware of any caveats? I couldn't find any closed issues on the topic.

**Comment by richm** [comment]
> systemd-timesyncd offers very basic NTP time synchronization support, but is often times sufficient. Is there a reason why this Ansible system role does not support it?

Not that I'm aware of.  The purpose of the role is to hide the implementation details from you e.g. I want to ensure that there is a timesync configured on the system, and the role is opinionated and provides guidance about the provider and config settings for the given platform.  In other words - what is the use case that you would want to use systemd-timesyncd instead of chronyd, assuming you didn't know or care what is the default timesync provider?

> If not, is there an interest to receive a pull request for this? Has it maybe been tried before and should I be aware of any caveats? I couldn't find any closed issues on the topic.

I think it would be relatively straightforward to add `systemd-timesyncd` as a provider.  One caveat is that if this provider is very basic, I'm assuming many/most of the parameters would not be applicable?  So documenting that and handling that in the role might be tricky e.g. how do you tell the user that `timesync_some_setting` is not applicable to the chosen provider?  Or the documentation will be sufficient that the users knows if they set `timesync_provider: systemd-timesyncd` then they cannot set `timesync_some_setting` which is not applicable to that provider?

**Comment by rmbleeker** [comment]
> what is the use case that you would want to use systemd-timesyncd instead of chronyd, assuming you didn't know or care what is the default timesync provider?

Exactly that. I don't care about the default timesync provider, even if it's something as minimal as systemd-timesyncd. However there are systems on which people might care about additional packages being installed and services being started, consuming presumably limited storage space, memory and CPU power. Things like the Raspberry Pi and other low spec (ARM based) hardware comes to mind.

My personal use case would be for a couple of Raspberry Pi systems, but after digging around in this role a bit more I realized that it is not officially compatible with the Debian based Linux distributions that are prevalent on the Pi, so that would be something to look at first in that case.

So it seems my request was ill considered, you may close it at your convenience.

**Comment by richm** [comment]
> > what is the use case that you would want to use systemd-timesyncd instead of chronyd, assuming you didn't know or care what is the default timesync provider?
> 
> Exactly that. I don't care about the default timesync provider, even if it's something as minimal as systemd-timesyncd. However there are systems on which people might care about additional packages being installed and services being started, consuming presumably limited storage space, memory and CPU power. Things like the Raspberry Pi and other low spec (ARM based) hardware comes to mind.
> 
> My personal use case would be for a couple of Raspberry Pi systems, but after digging around in this role a bit more I realized that it is not officially compatible with the Debian based Linux distributions

If you can use Ansible to manage those platforms, you can modify the role to support those platforms.  There are system roles other than timesync that support ubuntu/debian - see https://github.com/linux-system-roles/ssh/tree/master/vars

> that are prevalent on the Pi, so that would be something to look at first in that case.
> 
> So it seems my request was ill considered, you may close it at your convenience.

**Comment by mlichvar** [comment]
> Exactly that. I don't care about the default timesync provider, even if it's something as minimal as systemd-timesyncd.

My opinion is that if you don't need a synchronized clock, you shouldn't enable any NTP clients. That's the most secure configuration. If you need a synchronized clock, but don't know the specifics of each implementations, you generally want something a bit more robust than timesyncd. For a use case of NTP over Internet, I'd consider something like openntpd or the busybox ntpd as the absolute minimum.

> However there are systems on which people might care about additional packages being installed and services being started, consuming presumably limited storage space, memory and CPU power. Things like the Raspberry Pi and other low spec (ARM based) hardware comes to mind.

In order to save a significant amount of storage or RAM, you might need to replace systemd first (on which timesyncd depends). Small devices like routers (e.g. 4-16 MB of flash and 32-128 MB RAM) typically run the busybox ntpd.

Anyway, timesyncd doesn't support most of the options that this role has and behaves very differently from the supported implementations, so I don't think it would be a good fit.
