### ISSUE TITLE
error in task Get chrony version

### ISSUE THREAD

**Issue by iLeonelPerea** [linux-system-roles/timesync#8]
I am using Ubuntu and in the task `Get chrony version` get the following error:

`package chrony is not installed`

**Comment by pcahyna** [comment]
Ubuntu is the controller host, or the managed host?

**Comment by mlichvar** [comment]
The problem is in the rpm command used to get the package version. It would be weird if it worked on Ubuntu :).

If there is a module that can get the version of packages on different systems, we could use that. However, there are other differences between Fedora/RHEL and Debian/Ubuntu, e.g. different path of chrony.conf, so more work would be needed to support the other distros..

**Comment by pcahyna** [comment]
We have some changes in progress that will eliminate the calls to rpm and use a distribution-agnostic method. As said above, more work would be needed to support Debian/Ubuntu, though.

**Comment by pcahyna** [comment]
contributed change to support Ubuntu: #62
